#!/usr/bin/env bash
#
# unlink-dotfiles

set -e
source `pwd`/common.sh

# ----------------------------------------------------------------------------
# Defaults:
# ---------
os=$(detect_os)
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# Parse Arguments:
# ----------------
while [[ $# -gt 1 ]]
do
  key="$1"
  shift

  case $key in
    -o|--os )
      os="$1"
      shift
      ;;
    * )
      # unknown option
      ;;
  esac
done

check_dotfiles_root_provided $1
# ----------------------------------------------------------------------------

check_dotfiles_are_symbolic_links () {
  for source in $(find_dotfile_symlinks $dotfiles_root $os)
  do
    dest=$(determine_dotfile_destination $source)
    if [[ -e $dest && ! -L $dest ]]; then
        fail "All dotfiles must be symbolic links. $dest is not."
    fi
  done
}

unlink_dotfiles () {
  info 'Unlinking dotfiles'

  for source in $(find_dotfile_symlinks $dotfiles_root $os)
  do
    dest=$(determine_dotfile_destination $source)
    if [[ -L $dest ]]; then
      remove_link $dest
    fi
  done

}

echo ''
check_dotfiles_are_symbolic_links
unlink_dotfiles
